// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQF8KhUVEmUpw_Z40J0oJc8xSt_Bm0uo',
    appId: '1:939312490837:web:d01b205a8783fb219b27dc',
    messagingSenderId: '939312490837',
    projectId: 'goatapp-b4e08',
    authDomain: 'goatapp-b4e08.firebaseapp.com',
    storageBucket: 'goatapp-b4e08.appspot.com',
    measurementId: 'G-L48WE224EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHowjyZQ8V-_pEoz7CrA050nRbcfHCqA',
    appId: '1:939312490837:android:3e028b53a5abd86e9b27dc',
    messagingSenderId: '939312490837',
    projectId: 'goatapp-b4e08',
    storageBucket: 'goatapp-b4e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPBdcwEI_G-9FSLkAB5WL95QktBdeI8Y0',
    appId: '1:939312490837:ios:0c995893fae984c59b27dc',
    messagingSenderId: '939312490837',
    projectId: 'goatapp-b4e08',
    storageBucket: 'goatapp-b4e08.appspot.com',
    iosClientId:
        '939312490837-vp1cqa4r7tneosjd4akri8aa23vdnotp.apps.googleusercontent.com',
    iosBundleId: 'com.example.goatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPBdcwEI_G-9FSLkAB5WL95QktBdeI8Y0',
    appId: '1:939312490837:ios:0c995893fae984c59b27dc',
    messagingSenderId: '939312490837',
    projectId: 'goatapp-b4e08',
    storageBucket: 'goatapp-b4e08.appspot.com',
    iosClientId:
        '939312490837-vp1cqa4r7tneosjd4akri8aa23vdnotp.apps.googleusercontent.com',
    iosBundleId: 'com.example.goatApp',
  );
}
